---
version: '2'
services:
    braavos:
        image: confluentinc/cp-zookeeper:5.5.4
        hostname: braavos
        container_name: braavos
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVERS: 'braavos:2888:3888;pentos:2888:3888;volantis:42888:43888'
    pentos:
        image: confluentinc/cp-zookeeper:5.5.4
        hostname: pentos
        container_name: pentos
        ports:
            - "2182:2181"
        environment:
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVERS: 'braavos:2888:3888;pentos:2888:3888;volantis:42888:43888'
    volantis:
        image: confluentinc/cp-zookeeper:5.5.4
        hostname: volantis
        container_name: volantis
        ports:
            - "2183:2181"
        environment:
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVERS: 'braavos:2888:3888;pentos:2888:3888;volantis:42888:43888'

    winterfell:
        image: confluentinc/cp-enterprise-kafka:5.5.4
        hostname: winterfell
        container_name: winterfell
        depends_on:
            - braavos
            - pentos
            - volantis
        ports:
            - "9092:9092"
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: 'braavos:2181,pentos:2182,volantis:2183'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://winterfell:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: winterfell:9092
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: braavos:2181,pentos:2182,volantis:2183
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

    casterly-rock:
        image: confluentinc/cp-enterprise-kafka:5.5.4
        hostname: casterly-rock
        container_name: casterly-rock
        depends_on:
            - braavos
            - pentos
            - volantis
        ports:
            - "9093:9093"
            - "29093:29093"
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: 'braavos:2181,pentos:2182,volantis:2183'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://casterly-rock:9093,PLAINTEXT_HOST://localhost:29093
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: casterly-rock:9093
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: braavos:2181,pentos:2182,volantis:2183
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

    riverrun:
        image: confluentinc/cp-enterprise-kafka:5.5.4
        hostname: riverrun
        container_name: riverrun
        depends_on:
            - braavos
            - pentos
            - volantis
        ports:
            - "9094:9094"
            - "29094:29094"
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: 'braavos:2181,pentos:2182,volantis:2183'
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://riverrun:9094,PLAINTEXT_HOST://localhost:29094
            KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: riverrun:9094
            CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: braavos:2181,pentos:2182,volantis:2183
            CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
            CONFLUENT_METRICS_ENABLE: 'true'
            CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

    schema-registry:
        image: confluentinc/cp-schema-registry:5.5.4
        hostname: schema-registry
        container_name: schema-registry
        depends_on:
            - braavos
            - pentos
            - volantis
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'braavos:2181,pentos:2182,volantis:2183'

    iron-bank:
        image: confluentinc/cp-enterprise-control-center:5.0.1
        container_name: control-center
        depends_on:
            - riverrun
            - winterfell
            - casterly-rock
            - schema-registry
            - pentos
            - braavos
            - volantis
        ports:
            - "9021:9021"
        environment:
            CONTROL_CENTER_BOOTSTRAP_SERVERS: "winterfell:9092,casterly-rock:9093,riverrun:9094"
            CONTROL_CENTER_ZOOKEEPER_CONNECT: "braavos:2181,pentos:2182,volantis:2183"
            CONTROL_CENTER_REPLICATION_FACTOR: 2
            CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION: 2
            CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 2
            CONTROL_CENTER_COMMAND_TOPIC_REPLICATION: 2
            CONTROL_CENTER_METRICS_TOPIC_REPLICATION: 2
            CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS: 2
            CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schemaregistry:8081"
            CONTROL_CENTER_STREAMS_CONSUMER_REQUEST_TIMEOUT_MS: "960032"
            CONTROL_CENTER_ID: "MY_C3"